version: "3.8"
services:
  db:
    container_name: mysql
    image: mysql:8.0.36
    env_file:
      - ./.env
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  client:
    container_name: react
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - ./.env
    restart: always
    #dev
    volumes:
      - ./client/app:/app
    tty: true
    depends_on:
      - server
      - db
    ports:
      - "3000:3000"
  server:
    container_name: golang
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./.env
    restart: always
    #dev
    volumes:
      - ./server:/src
    #dev
    command: air -c .air.toml
    tty: true
    depends_on:
      - db
    ports:
      - "3001:3001"
  proxy:
    container_name: nginx
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    volumes:
      - ./proxy/log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - client
  cache-store:
    container_name: redis
    image: redis:7.2.4
    tty: true
    restart: always
    depends_on:
      - server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
